// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sunima/tfhe/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryCiphertextByIdRequest struct {
	// id is the 32-byte sha256 content address (hex-encoded in the URL).
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryCiphertextByIdRequest) Reset()         { *m = QueryCiphertextByIdRequest{} }
func (m *QueryCiphertextByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCiphertextByIdRequest) ProtoMessage()    {}
func (*QueryCiphertextByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{0}
}
func (m *QueryCiphertextByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCiphertextByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCiphertextByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCiphertextByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCiphertextByIdRequest.Merge(m, src)
}
func (m *QueryCiphertextByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCiphertextByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCiphertextByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCiphertextByIdRequest proto.InternalMessageInfo

func (m *QueryCiphertextByIdRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type QueryCiphertextByIdResponse struct {
	Ciphertext Ciphertext `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext"`
}

func (m *QueryCiphertextByIdResponse) Reset()         { *m = QueryCiphertextByIdResponse{} }
func (m *QueryCiphertextByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCiphertextByIdResponse) ProtoMessage()    {}
func (*QueryCiphertextByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{1}
}
func (m *QueryCiphertextByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCiphertextByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCiphertextByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCiphertextByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCiphertextByIdResponse.Merge(m, src)
}
func (m *QueryCiphertextByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCiphertextByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCiphertextByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCiphertextByIdResponse proto.InternalMessageInfo

func (m *QueryCiphertextByIdResponse) GetCiphertext() Ciphertext {
	if m != nil {
		return m.Ciphertext
	}
	return Ciphertext{}
}

type QueryOwnedCiphertextsRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryOwnedCiphertextsRequest) Reset()         { *m = QueryOwnedCiphertextsRequest{} }
func (m *QueryOwnedCiphertextsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOwnedCiphertextsRequest) ProtoMessage()    {}
func (*QueryOwnedCiphertextsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{2}
}
func (m *QueryOwnedCiphertextsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOwnedCiphertextsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOwnedCiphertextsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOwnedCiphertextsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOwnedCiphertextsRequest.Merge(m, src)
}
func (m *QueryOwnedCiphertextsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOwnedCiphertextsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOwnedCiphertextsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOwnedCiphertextsRequest proto.InternalMessageInfo

func (m *QueryOwnedCiphertextsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryOwnedCiphertextsResponse struct {
	Ids [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (m *QueryOwnedCiphertextsResponse) Reset()         { *m = QueryOwnedCiphertextsResponse{} }
func (m *QueryOwnedCiphertextsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOwnedCiphertextsResponse) ProtoMessage()    {}
func (*QueryOwnedCiphertextsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{3}
}
func (m *QueryOwnedCiphertextsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOwnedCiphertextsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOwnedCiphertextsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOwnedCiphertextsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOwnedCiphertextsResponse.Merge(m, src)
}
func (m *QueryOwnedCiphertextsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOwnedCiphertextsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOwnedCiphertextsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOwnedCiphertextsResponse proto.InternalMessageInfo

func (m *QueryOwnedCiphertextsResponse) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type QueryAttestersRequest struct {
}

func (m *QueryAttestersRequest) Reset()         { *m = QueryAttestersRequest{} }
func (m *QueryAttestersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttestersRequest) ProtoMessage()    {}
func (*QueryAttestersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{4}
}
func (m *QueryAttestersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestersRequest.Merge(m, src)
}
func (m *QueryAttestersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestersRequest proto.InternalMessageInfo

type QueryAttestersResponse struct {
	Attesters []Attester `protobuf:"bytes,1,rep,name=attesters,proto3" json:"attesters"`
}

func (m *QueryAttestersResponse) Reset()         { *m = QueryAttestersResponse{} }
func (m *QueryAttestersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttestersResponse) ProtoMessage()    {}
func (*QueryAttestersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{5}
}
func (m *QueryAttestersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestersResponse.Merge(m, src)
}
func (m *QueryAttestersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestersResponse proto.InternalMessageInfo

func (m *QueryAttestersResponse) GetAttesters() []Attester {
	if m != nil {
		return m.Attesters
	}
	return nil
}

type QueryDecryptionRequestRequest struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryDecryptionRequestRequest) Reset()         { *m = QueryDecryptionRequestRequest{} }
func (m *QueryDecryptionRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDecryptionRequestRequest) ProtoMessage()    {}
func (*QueryDecryptionRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{6}
}
func (m *QueryDecryptionRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDecryptionRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDecryptionRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDecryptionRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDecryptionRequestRequest.Merge(m, src)
}
func (m *QueryDecryptionRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDecryptionRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDecryptionRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDecryptionRequestRequest proto.InternalMessageInfo

func (m *QueryDecryptionRequestRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type QueryDecryptionRequestResponse struct {
	Request DecryptionRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request"`
}

func (m *QueryDecryptionRequestResponse) Reset()         { *m = QueryDecryptionRequestResponse{} }
func (m *QueryDecryptionRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDecryptionRequestResponse) ProtoMessage()    {}
func (*QueryDecryptionRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{7}
}
func (m *QueryDecryptionRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDecryptionRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDecryptionRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDecryptionRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDecryptionRequestResponse.Merge(m, src)
}
func (m *QueryDecryptionRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDecryptionRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDecryptionRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDecryptionRequestResponse proto.InternalMessageInfo

func (m *QueryDecryptionRequestResponse) GetRequest() DecryptionRequest {
	if m != nil {
		return m.Request
	}
	return DecryptionRequest{}
}

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{8}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bd956a4b203877, []int{9}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*QueryCiphertextByIdRequest)(nil), "sunima.tfhe.v1.QueryCiphertextByIdRequest")
	proto.RegisterType((*QueryCiphertextByIdResponse)(nil), "sunima.tfhe.v1.QueryCiphertextByIdResponse")
	proto.RegisterType((*QueryOwnedCiphertextsRequest)(nil), "sunima.tfhe.v1.QueryOwnedCiphertextsRequest")
	proto.RegisterType((*QueryOwnedCiphertextsResponse)(nil), "sunima.tfhe.v1.QueryOwnedCiphertextsResponse")
	proto.RegisterType((*QueryAttestersRequest)(nil), "sunima.tfhe.v1.QueryAttestersRequest")
	proto.RegisterType((*QueryAttestersResponse)(nil), "sunima.tfhe.v1.QueryAttestersResponse")
	proto.RegisterType((*QueryDecryptionRequestRequest)(nil), "sunima.tfhe.v1.QueryDecryptionRequestRequest")
	proto.RegisterType((*QueryDecryptionRequestResponse)(nil), "sunima.tfhe.v1.QueryDecryptionRequestResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "sunima.tfhe.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "sunima.tfhe.v1.QueryParamsResponse")
}

func init() { proto.RegisterFile("sunima/tfhe/v1/query.proto", fileDescriptor_79bd956a4b203877) }

var fileDescriptor_79bd956a4b203877 = []byte{
	// 632 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0xbb, 0xf0, 0x83, 0x5f, 0x78, 0x20, 0x04, 0x47, 0xc4, 0xb2, 0xc0, 0x02, 0x6b, 0x10,
	0x54, 0xd8, 0x09, 0xd5, 0xa3, 0x07, 0x5b, 0x3d, 0x68, 0x4c, 0xfc, 0x53, 0x13, 0x0f, 0x5e, 0x9a,
	0x6d, 0x77, 0xdc, 0x6e, 0x42, 0x77, 0xb6, 0x3b, 0xd3, 0x42, 0x43, 0x7a, 0xf1, 0x15, 0x18, 0x4d,
	0x7c, 0x03, 0xbe, 0x05, 0x5f, 0x04, 0x17, 0x13, 0xa2, 0x17, 0x4f, 0xc6, 0xb4, 0xbe, 0x10, 0xb3,
	0x33, 0xb3, 0x2d, 0x1d, 0xba, 0xda, 0xdb, 0xf0, 0x3c, 0xcf, 0xf7, 0xf9, 0x7e, 0x66, 0xe7, 0x4b,
	0xc1, 0x64, 0xad, 0x30, 0x68, 0xb8, 0x98, 0xbf, 0xad, 0x13, 0xdc, 0x3e, 0xc4, 0xcd, 0x16, 0x89,
	0x3b, 0x4e, 0x14, 0x53, 0x4e, 0xd1, 0xa2, 0xec, 0x39, 0x49, 0xcf, 0x69, 0x1f, 0x9a, 0xab, 0x35,
	0xca, 0x1a, 0x94, 0x55, 0x44, 0x17, 0xcb, 0x3f, 0xe4, 0xa8, 0xb9, 0xec, 0x53, 0x9f, 0xca, 0x7a,
	0x72, 0x52, 0xd5, 0x75, 0x9f, 0x52, 0xff, 0x88, 0x60, 0x37, 0x0a, 0xb0, 0x1b, 0x86, 0x94, 0xbb,
	0x3c, 0xa0, 0x61, 0xaa, 0x59, 0xd5, 0xac, 0x85, 0x8d, 0x68, 0xd9, 0xfb, 0x60, 0xbe, 0x4c, 0x40,
	0x1e, 0x06, 0x51, 0x9d, 0xc4, 0x9c, 0x9c, 0xf0, 0x52, 0xe7, 0x89, 0x57, 0x26, 0xcd, 0x16, 0x61,
	0x1c, 0x2d, 0xc2, 0x54, 0xe0, 0xe5, 0x8d, 0x2d, 0x63, 0x6f, 0xa1, 0x3c, 0x15, 0x78, 0x76, 0x05,
	0xd6, 0xc6, 0x4e, 0xb3, 0x88, 0x86, 0x8c, 0xa0, 0x07, 0x00, 0xb5, 0x41, 0x47, 0xc8, 0xe6, 0x0b,
	0xa6, 0x33, 0x7a, 0x37, 0xe7, 0x82, 0xf6, 0xbf, 0xb3, 0x9f, 0x9b, 0xb9, 0xf2, 0x05, 0x8d, 0xfd,
	0x0c, 0xd6, 0x85, 0xc1, 0xf3, 0xe3, 0x90, 0x78, 0xc3, 0x49, 0x96, 0x02, 0x39, 0x30, 0x43, 0x8f,
	0x43, 0x12, 0x8b, 0xe5, 0x73, 0xa5, 0xfc, 0xb7, 0x2f, 0x07, 0xcb, 0xea, 0xf3, 0x14, 0x3d, 0x2f,
	0x26, 0x8c, 0xbd, 0xe2, 0x71, 0x10, 0xfa, 0x65, 0x39, 0x66, 0x1f, 0xc2, 0x46, 0xc6, 0x3e, 0x85,
	0xbc, 0x04, 0xd3, 0x81, 0xc7, 0xf2, 0xc6, 0xd6, 0xf4, 0xde, 0x42, 0x39, 0x39, 0xda, 0xd7, 0xe1,
	0x9a, 0x90, 0x14, 0x39, 0x27, 0x8c, 0x93, 0x38, 0xf5, 0xb6, 0x5f, 0xc3, 0x8a, 0xde, 0x50, 0x4b,
	0xee, 0xc3, 0x9c, 0x9b, 0x16, 0xc5, 0xaa, 0xf9, 0x42, 0x5e, 0xbf, 0x76, 0xaa, 0x52, 0x97, 0x1e,
	0x0a, 0x6c, 0xac, 0x18, 0x1f, 0x91, 0x5a, 0xdc, 0x89, 0x92, 0x77, 0x53, 0x8e, 0x59, 0xaf, 0x50,
	0x03, 0x2b, 0x4b, 0xa0, 0x80, 0x8a, 0xf0, 0x7f, 0x2c, 0x4b, 0xea, 0x15, 0xb6, 0x75, 0x9c, 0x4b,
	0x5a, 0xc5, 0x95, 0xea, 0xec, 0x65, 0x40, 0xc2, 0xe4, 0x85, 0x1b, 0xbb, 0x8d, 0xc1, 0x37, 0x78,
	0x0a, 0x57, 0x47, 0xaa, 0xca, 0xef, 0x1e, 0xcc, 0x46, 0xa2, 0xa2, 0xec, 0x56, 0x74, 0x3b, 0x39,
	0xaf, 0x3c, 0xd4, 0x6c, 0xe1, 0xeb, 0x0c, 0xcc, 0x88, 0x6d, 0xe8, 0x83, 0x01, 0x8b, 0xa3, 0x99,
	0x42, 0xb7, 0xf5, 0x15, 0xd9, 0x31, 0x35, 0xef, 0x4c, 0x34, 0x2b, 0x59, 0xed, 0xdd, 0x77, 0xdf,
	0x7f, 0x7f, 0x9c, 0xda, 0x46, 0x9b, 0x58, 0xfb, 0xaf, 0x18, 0xc6, 0x10, 0x9f, 0x06, 0x5e, 0x17,
	0x7d, 0x32, 0x60, 0x49, 0xcf, 0x0d, 0xda, 0x1f, 0x6b, 0x95, 0x11, 0x57, 0xf3, 0x60, 0xc2, 0x69,
	0x85, 0xb6, 0x23, 0xd0, 0x36, 0xd1, 0x86, 0x8e, 0x96, 0x84, 0xd9, 0xc3, 0xa7, 0x22, 0xd3, 0x5d,
	0xd4, 0x85, 0xb9, 0x41, 0x06, 0xd1, 0xce, 0x58, 0x0b, 0x3d, 0xbc, 0xe6, 0xcd, 0x7f, 0x8d, 0x29,
	0x84, 0x6d, 0x81, 0xb0, 0x86, 0x56, 0x75, 0x84, 0x41, 0x5e, 0xd1, 0x67, 0x03, 0xae, 0x5c, 0x8a,
	0x0f, 0x1a, 0x7f, 0xd5, 0xac, 0x4c, 0x9b, 0xce, 0xa4, 0xe3, 0x8a, 0x0b, 0x0b, 0xae, 0x5b, 0x68,
	0x57, 0xe7, 0xf2, 0x06, 0x92, 0x8a, 0x8a, 0xae, 0x7c, 0xbd, 0x26, 0xcc, 0xca, 0xd0, 0x21, 0x7b,
	0xac, 0xd5, 0x48, 0xae, 0xcd, 0x1b, 0x7f, 0x9d, 0x51, 0x0c, 0x96, 0x60, 0xc8, 0xa3, 0x15, 0x9d,
	0x41, 0xe6, 0xb9, 0xf4, 0xf8, 0xac, 0x67, 0x19, 0xe7, 0x3d, 0xcb, 0xf8, 0xd5, 0xb3, 0x8c, 0xf7,
	0x7d, 0x2b, 0x77, 0xde, 0xb7, 0x72, 0x3f, 0xfa, 0x56, 0xee, 0x8d, 0xe3, 0x07, 0xbc, 0xde, 0xaa,
	0x3a, 0x35, 0xda, 0x50, 0xda, 0x83, 0x23, 0xb7, 0xca, 0xd2, 0x33, 0x69, 0x37, 0xf0, 0x89, 0xdc,
	0xc6, 0x3b, 0x11, 0x61, 0xd5, 0x59, 0xf1, 0xe3, 0x7c, 0xf7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc3, 0xc2, 0xc0, 0x76, 0x34, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// CiphertextById returns a stored ciphertext by its content hash.
	CiphertextById(ctx context.Context, in *QueryCiphertextByIdRequest, opts ...grpc.CallOption) (*QueryCiphertextByIdResponse, error)
	// OwnedCiphertexts lists ciphertext ids owned by a given address.
	OwnedCiphertexts(ctx context.Context, in *QueryOwnedCiphertextsRequest, opts ...grpc.CallOption) (*QueryOwnedCiphertextsResponse, error)
	// Attesters lists registered attesters.
	Attesters(ctx context.Context, in *QueryAttestersRequest, opts ...grpc.CallOption) (*QueryAttestersResponse, error)
	// DecryptionRequest returns the status of a pending decryption flow.
	DecryptionRequest(ctx context.Context, in *QueryDecryptionRequestRequest, opts ...grpc.CallOption) (*QueryDecryptionRequestResponse, error)
	// Params returns the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CiphertextById(ctx context.Context, in *QueryCiphertextByIdRequest, opts ...grpc.CallOption) (*QueryCiphertextByIdResponse, error) {
	out := new(QueryCiphertextByIdResponse)
	err := c.cc.Invoke(ctx, "/sunima.tfhe.v1.Query/CiphertextById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OwnedCiphertexts(ctx context.Context, in *QueryOwnedCiphertextsRequest, opts ...grpc.CallOption) (*QueryOwnedCiphertextsResponse, error) {
	out := new(QueryOwnedCiphertextsResponse)
	err := c.cc.Invoke(ctx, "/sunima.tfhe.v1.Query/OwnedCiphertexts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Attesters(ctx context.Context, in *QueryAttestersRequest, opts ...grpc.CallOption) (*QueryAttestersResponse, error) {
	out := new(QueryAttestersResponse)
	err := c.cc.Invoke(ctx, "/sunima.tfhe.v1.Query/Attesters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DecryptionRequest(ctx context.Context, in *QueryDecryptionRequestRequest, opts ...grpc.CallOption) (*QueryDecryptionRequestResponse, error) {
	out := new(QueryDecryptionRequestResponse)
	err := c.cc.Invoke(ctx, "/sunima.tfhe.v1.Query/DecryptionRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/sunima.tfhe.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// CiphertextById returns a stored ciphertext by its content hash.
	CiphertextById(context.Context, *QueryCiphertextByIdRequest) (*QueryCiphertextByIdResponse, error)
	// OwnedCiphertexts lists ciphertext ids owned by a given address.
	OwnedCiphertexts(context.Context, *QueryOwnedCiphertextsRequest) (*QueryOwnedCiphertextsResponse, error)
	// Attesters lists registered attesters.
	Attesters(context.Context, *QueryAttestersRequest) (*QueryAttestersResponse, error)
	// DecryptionRequest returns the status of a pending decryption flow.
	DecryptionRequest(context.Context, *QueryDecryptionRequestRequest) (*QueryDecryptionRequestResponse, error)
	// Params returns the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) CiphertextById(ctx context.Context, req *QueryCiphertextByIdRequest) (*QueryCiphertextByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CiphertextById not implemented")
}
func (*UnimplementedQueryServer) OwnedCiphertexts(ctx context.Context, req *QueryOwnedCiphertextsRequest) (*QueryOwnedCiphertextsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OwnedCiphertexts not implemented")
}
func (*UnimplementedQueryServer) Attesters(ctx context.Context, req *QueryAttestersRequest) (*QueryAttestersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attesters not implemented")
}
func (*UnimplementedQueryServer) DecryptionRequest(ctx context.Context, req *QueryDecryptionRequestRequest) (*QueryDecryptionRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptionRequest not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CiphertextById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCiphertextByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CiphertextById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sunima.tfhe.v1.Query/CiphertextById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CiphertextById(ctx, req.(*QueryCiphertextByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OwnedCiphertexts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOwnedCiphertextsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OwnedCiphertexts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sunima.tfhe.v1.Query/OwnedCiphertexts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OwnedCiphertexts(ctx, req.(*QueryOwnedCiphertextsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Attesters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Attesters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sunima.tfhe.v1.Query/Attesters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Attesters(ctx, req.(*QueryAttestersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DecryptionRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDecryptionRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DecryptionRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sunima.tfhe.v1.Query/DecryptionRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DecryptionRequest(ctx, req.(*QueryDecryptionRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sunima.tfhe.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sunima.tfhe.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CiphertextById",
			Handler:    _Query_CiphertextById_Handler,
		},
		{
			MethodName: "OwnedCiphertexts",
			Handler:    _Query_OwnedCiphertexts_Handler,
		},
		{
			MethodName: "Attesters",
			Handler:    _Query_Attesters_Handler,
		},
		{
			MethodName: "DecryptionRequest",
			Handler:    _Query_DecryptionRequest_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sunima/tfhe/v1/query.proto",
}

func (m *QueryCiphertextByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCiphertextByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCiphertextByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCiphertextByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCiphertextByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCiphertextByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Ciphertext.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryOwnedCiphertextsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOwnedCiphertextsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOwnedCiphertextsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOwnedCiphertextsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOwnedCiphertextsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOwnedCiphertextsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for iNdEx := len(m.Ids) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Ids[iNdEx])
			copy(dAtA[i:], m.Ids[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Ids[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAttestersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAttestersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attesters) > 0 {
		for iNdEx := len(m.Attesters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attesters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDecryptionRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDecryptionRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDecryptionRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDecryptionRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDecryptionRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDecryptionRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCiphertextByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCiphertextByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Ciphertext.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryOwnedCiphertextsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOwnedCiphertextsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, b := range m.Ids {
			l = len(b)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAttestersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAttestersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attesters) > 0 {
		for _, e := range m.Attesters {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryDecryptionRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDecryptionRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Request.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCiphertextByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCiphertextByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCiphertextByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCiphertextByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCiphertextByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCiphertextByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ciphertext.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOwnedCiphertextsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOwnedCiphertextsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOwnedCiphertextsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOwnedCiphertextsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOwnedCiphertextsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOwnedCiphertextsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ids", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ids = append(m.Ids, make([]byte, postIndex-iNdEx))
			copy(m.Ids[len(m.Ids)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attesters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attesters = append(m.Attesters, Attester{})
			if err := m.Attesters[len(m.Attesters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDecryptionRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDecryptionRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDecryptionRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDecryptionRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDecryptionRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDecryptionRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
