// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sunima/tfhe/v1/tfhe.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Ciphertext is a stored TFHE ciphertext addressed by sha256(data).
type Ciphertext struct {
	// id is sha256(data); 32 bytes.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// data is the bincode-serialised tfhe-rs ciphertext blob.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// owner is the bech32 address that submitted the deposit.
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// created_at is the unix nanos at which the ciphertext was stored.
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Ciphertext) Reset()         { *m = Ciphertext{} }
func (m *Ciphertext) String() string { return proto.CompactTextString(m) }
func (*Ciphertext) ProtoMessage()    {}
func (*Ciphertext) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a3d1fecf800b37, []int{0}
}
func (m *Ciphertext) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ciphertext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ciphertext.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ciphertext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ciphertext.Merge(m, src)
}
func (m *Ciphertext) XXX_Size() int {
	return m.Size()
}
func (m *Ciphertext) XXX_DiscardUnknown() {
	xxx_messageInfo_Ciphertext.DiscardUnknown(m)
}

var xxx_messageInfo_Ciphertext proto.InternalMessageInfo

func (m *Ciphertext) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Ciphertext) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Ciphertext) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Ciphertext) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// Attester is a registered member of the threshold-decryption quorum.
// 5-of-9 quorum logic lives in Stage 5.3 and is not exercised in Stage 5.1.
type Attester struct {
	// address is the attester's bech32 address.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// pubkey is the ed25519 attestation signing key.
	Pubkey []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// share_pubkey verifies the attester's threshold share in the FHE keyset.
	SharePubkey []byte `protobuf:"bytes,3,opt,name=share_pubkey,json=sharePubkey,proto3" json:"share_pubkey,omitempty"`
	// registered_at is the unix nanos at which the attester was added.
	RegisteredAt int64 `protobuf:"varint,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
}

func (m *Attester) Reset()         { *m = Attester{} }
func (m *Attester) String() string { return proto.CompactTextString(m) }
func (*Attester) ProtoMessage()    {}
func (*Attester) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a3d1fecf800b37, []int{1}
}
func (m *Attester) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attester) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attester.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attester) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attester.Merge(m, src)
}
func (m *Attester) XXX_Size() int {
	return m.Size()
}
func (m *Attester) XXX_DiscardUnknown() {
	xxx_messageInfo_Attester.DiscardUnknown(m)
}

var xxx_messageInfo_Attester proto.InternalMessageInfo

func (m *Attester) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Attester) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Attester) GetSharePubkey() []byte {
	if m != nil {
		return m.SharePubkey
	}
	return nil
}

func (m *Attester) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

// DecryptionRequest tracks a pending threshold-decryption flow.
type DecryptionRequest struct {
	// id uniquely identifies this request (random 32 bytes).
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ciphertext_id is the target ciphertext.
	CiphertextId []byte `protobuf:"bytes,2,opt,name=ciphertext_id,json=ciphertextId,proto3" json:"ciphertext_id,omitempty"`
	// recipient is the bech32 address that will receive the plaintext.
	Recipient string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// partials is the list of submitted partial decryptions.
	Partials [][]byte `protobuf:"bytes,4,rep,name=partials,proto3" json:"partials,omitempty"`
	// attesters is the list of bech32 addresses of submitting attesters.
	Attesters []string `protobuf:"bytes,5,rep,name=attesters,proto3" json:"attesters,omitempty"`
	// status: 0 pending, 1 quorum_reached, 2 delivered, 3 expired.
	Status uint32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// expires_at is the unix nanos after which the request is invalid.
	ExpiresAt int64 `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *DecryptionRequest) Reset()         { *m = DecryptionRequest{} }
func (m *DecryptionRequest) String() string { return proto.CompactTextString(m) }
func (*DecryptionRequest) ProtoMessage()    {}
func (*DecryptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a3d1fecf800b37, []int{2}
}
func (m *DecryptionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DecryptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DecryptionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DecryptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptionRequest.Merge(m, src)
}
func (m *DecryptionRequest) XXX_Size() int {
	return m.Size()
}
func (m *DecryptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptionRequest proto.InternalMessageInfo

func (m *DecryptionRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DecryptionRequest) GetCiphertextId() []byte {
	if m != nil {
		return m.CiphertextId
	}
	return nil
}

func (m *DecryptionRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *DecryptionRequest) GetPartials() [][]byte {
	if m != nil {
		return m.Partials
	}
	return nil
}

func (m *DecryptionRequest) GetAttesters() []string {
	if m != nil {
		return m.Attesters
	}
	return nil
}

func (m *DecryptionRequest) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DecryptionRequest) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

// Params defines the parameters for the x/tfhe module.
type Params struct {
	// min_attesters is the threshold for decryption quorum (typically 5 of 9).
	MinAttesters uint32 `protobuf:"varint,1,opt,name=min_attesters,json=minAttesters,proto3" json:"min_attesters,omitempty"`
	// decryption_window_blocks is the number of blocks a DecryptionRequest
	// remains open before transitioning to expired.
	DecryptionWindowBlocks uint64 `protobuf:"varint,2,opt,name=decryption_window_blocks,json=decryptionWindowBlocks,proto3" json:"decryption_window_blocks,omitempty"`
	// server_key is the bincode-serialised tfhe-rs server key, governance-set.
	// Production layout may move this to a dedicated module-account paged store
	// in a future stage if the blob outgrows what params can carry comfortably.
	ServerKey []byte `protobuf:"bytes,3,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a3d1fecf800b37, []int{3}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinAttesters() uint32 {
	if m != nil {
		return m.MinAttesters
	}
	return 0
}

func (m *Params) GetDecryptionWindowBlocks() uint64 {
	if m != nil {
		return m.DecryptionWindowBlocks
	}
	return 0
}

func (m *Params) GetServerKey() []byte {
	if m != nil {
		return m.ServerKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Ciphertext)(nil), "sunima.tfhe.v1.Ciphertext")
	proto.RegisterType((*Attester)(nil), "sunima.tfhe.v1.Attester")
	proto.RegisterType((*DecryptionRequest)(nil), "sunima.tfhe.v1.DecryptionRequest")
	proto.RegisterType((*Params)(nil), "sunima.tfhe.v1.Params")
}

func init() { proto.RegisterFile("sunima/tfhe/v1/tfhe.proto", fileDescriptor_f5a3d1fecf800b37) }

var fileDescriptor_f5a3d1fecf800b37 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xde, 0x69, 0xbb, 0xdd, 0xed, 0x98, 0x2e, 0xec, 0x50, 0x96, 0xb4, 0x60, 0x88, 0xdd, 0x4b,
	0x11, 0xb6, 0x65, 0x15, 0x44, 0xbc, 0xa5, 0x7a, 0x50, 0xbc, 0x2c, 0xf1, 0x20, 0x78, 0x09, 0xd3,
	0xe4, 0xd9, 0x0e, 0xdb, 0x64, 0xe2, 0xcc, 0xf4, 0xd7, 0xc9, 0xbb, 0x5e, 0xfc, 0x0b, 0x04, 0xff,
	0x03, 0x0f, 0xfe, 0x11, 0x1e, 0x17, 0x4f, 0x1e, 0xa5, 0x3d, 0xf8, 0x6f, 0x48, 0x66, 0xa6, 0x89,
	0x20, 0xac, 0x97, 0x64, 0xde, 0xf7, 0xbd, 0x7c, 0xef, 0xcb, 0x37, 0x3c, 0xdc, 0x95, 0x8b, 0x8c,
	0xa5, 0x74, 0xa4, 0xde, 0xce, 0x60, 0xb4, 0xbc, 0xd4, 0xef, 0x61, 0x2e, 0xb8, 0xe2, 0xe4, 0xc4,
	0x50, 0x43, 0x0d, 0x2d, 0x2f, 0x7b, 0xa7, 0x34, 0x65, 0x19, 0x1f, 0xe9, 0xa7, 0x69, 0xe9, 0x75,
	0x63, 0x2e, 0x53, 0x2e, 0x23, 0x5d, 0x8d, 0x4c, 0x61, 0xa9, 0xce, 0x94, 0x4f, 0xb9, 0xc1, 0x8b,
	0x93, 0x41, 0xfb, 0xef, 0x31, 0x7e, 0xca, 0xf2, 0x19, 0x08, 0x05, 0x6b, 0x45, 0x4e, 0x70, 0x8d,
	0x25, 0x2e, 0xf2, 0xd1, 0xc0, 0x09, 0x6b, 0x2c, 0x21, 0x04, 0x37, 0x12, 0xaa, 0xa8, 0x5b, 0xd3,
	0x88, 0x3e, 0x93, 0x21, 0x3e, 0xe4, 0xab, 0x0c, 0x84, 0x5b, 0xf7, 0xd1, 0xa0, 0x35, 0x76, 0x7f,
	0x7c, 0xbb, 0xe8, 0xd8, 0x41, 0x41, 0x92, 0x08, 0x90, 0xf2, 0x95, 0x12, 0x2c, 0x9b, 0x86, 0xa6,
	0x8d, 0xdc, 0xc5, 0x38, 0x16, 0x40, 0x15, 0x24, 0x11, 0x55, 0x6e, 0xc3, 0x47, 0x83, 0x7a, 0xd8,
	0xb2, 0x48, 0xa0, 0xfa, 0x9f, 0x11, 0x3e, 0x0e, 0x94, 0x02, 0xa9, 0x40, 0x90, 0x07, 0xf8, 0x88,
	0x1a, 0x0d, 0x6d, 0xe2, 0x36, 0xf5, 0x7d, 0x23, 0x39, 0xc3, 0xcd, 0x7c, 0x31, 0xb9, 0x86, 0x8d,
	0x75, 0x69, 0x2b, 0x72, 0x0f, 0x3b, 0x72, 0x46, 0x05, 0x44, 0x96, 0xad, 0x6b, 0xf6, 0x8e, 0xc6,
	0xae, 0x4c, 0xcb, 0x39, 0x6e, 0x0b, 0x98, 0xb2, 0x62, 0xf4, 0xdf, 0xee, 0x9c, 0x0a, 0x0c, 0x54,
	0xff, 0x63, 0x0d, 0x9f, 0x3e, 0x83, 0x58, 0x6c, 0x72, 0xc5, 0x78, 0x16, 0xc2, 0xbb, 0x05, 0xc8,
	0x7f, 0x93, 0x3a, 0xc7, 0xed, 0xb8, 0xcc, 0x31, 0x62, 0x89, 0x35, 0xe3, 0x54, 0xe0, 0x8b, 0x84,
	0x3c, 0xc2, 0x2d, 0x01, 0x31, 0xcb, 0x19, 0x64, 0xea, 0xbf, 0xf1, 0x55, 0xad, 0xa4, 0x87, 0x8f,
	0x73, 0x2a, 0x14, 0xa3, 0x73, 0xe9, 0x36, 0xfc, 0xfa, 0xc0, 0x09, 0xcb, 0xba, 0xd0, 0xa4, 0x36,
	0x3e, 0xe9, 0x1e, 0xfa, 0xf5, 0xdb, 0x35, 0xcb, 0xd6, 0x22, 0x36, 0xa9, 0xa8, 0x5a, 0x48, 0xb7,
	0xe9, 0xa3, 0x41, 0x3b, 0xb4, 0x55, 0x71, 0x5d, 0xb0, 0xce, 0x99, 0x00, 0x59, 0x04, 0x72, 0x64,
	0xae, 0xcb, 0x22, 0x81, 0xea, 0x7f, 0x41, 0xb8, 0x79, 0x45, 0x05, 0x4d, 0x65, 0xf1, 0xcb, 0x29,
	0xcb, 0xa2, 0x6a, 0x3a, 0xd2, 0x42, 0x4e, 0xca, 0xb2, 0xa0, 0x1c, 0xf3, 0x18, 0xbb, 0x49, 0x19,
	0x5e, 0xb4, 0x62, 0x59, 0xc2, 0x57, 0xd1, 0x64, 0xce, 0xe3, 0x6b, 0xa9, 0x23, 0x6a, 0x84, 0x67,
	0x15, 0xff, 0x5a, 0xd3, 0x63, 0xcd, 0x16, 0x46, 0x24, 0x88, 0x25, 0x88, 0xa8, 0xba, 0xbd, 0x96,
	0x41, 0x5e, 0xc2, 0xe6, 0x49, 0xf7, 0xc3, 0xef, 0xaf, 0xf7, 0x3b, 0x76, 0x59, 0xd6, 0x66, 0x5d,
	0x8c, 0xb1, 0xf1, 0xf3, 0xef, 0x5b, 0x0f, 0xdd, 0x6c, 0x3d, 0xf4, 0x6b, 0xeb, 0xa1, 0x4f, 0x3b,
	0xef, 0xe0, 0x66, 0xe7, 0x1d, 0xfc, 0xdc, 0x79, 0x07, 0x6f, 0x86, 0x53, 0xa6, 0x66, 0x8b, 0xc9,
	0x30, 0xe6, 0xe9, 0xc8, 0x7c, 0x7a, 0x31, 0xa7, 0x13, 0xb9, 0x3f, 0xc3, 0x32, 0xdd, 0x4b, 0xa9,
	0x4d, 0x0e, 0x72, 0xd2, 0xd4, 0x4b, 0xf2, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x48,
	0x4e, 0x3d, 0x95, 0x03, 0x00, 0x00,
}

func (m *Ciphertext) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ciphertext) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ciphertext) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintTfhe(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Attester) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attester) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attester) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegisteredAt != 0 {
		i = encodeVarintTfhe(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.SharePubkey) > 0 {
		i -= len(m.SharePubkey)
		copy(dAtA[i:], m.SharePubkey)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.SharePubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DecryptionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DecryptionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DecryptionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintTfhe(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintTfhe(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Attesters) > 0 {
		for iNdEx := len(m.Attesters) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Attesters[iNdEx])
			copy(dAtA[i:], m.Attesters[iNdEx])
			i = encodeVarintTfhe(dAtA, i, uint64(len(m.Attesters[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Partials) > 0 {
		for iNdEx := len(m.Partials) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Partials[iNdEx])
			copy(dAtA[i:], m.Partials[iNdEx])
			i = encodeVarintTfhe(dAtA, i, uint64(len(m.Partials[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CiphertextId) > 0 {
		i -= len(m.CiphertextId)
		copy(dAtA[i:], m.CiphertextId)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.CiphertextId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ServerKey) > 0 {
		i -= len(m.ServerKey)
		copy(dAtA[i:], m.ServerKey)
		i = encodeVarintTfhe(dAtA, i, uint64(len(m.ServerKey)))
		i--
		dAtA[i] = 0x1a
	}
	if m.DecryptionWindowBlocks != 0 {
		i = encodeVarintTfhe(dAtA, i, uint64(m.DecryptionWindowBlocks))
		i--
		dAtA[i] = 0x10
	}
	if m.MinAttesters != 0 {
		i = encodeVarintTfhe(dAtA, i, uint64(m.MinAttesters))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTfhe(dAtA []byte, offset int, v uint64) int {
	offset -= sovTfhe(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Ciphertext) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovTfhe(uint64(m.CreatedAt))
	}
	return n
}

func (m *Attester) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	l = len(m.SharePubkey)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovTfhe(uint64(m.RegisteredAt))
	}
	return n
}

func (m *DecryptionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	l = len(m.CiphertextId)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	if len(m.Partials) > 0 {
		for _, b := range m.Partials {
			l = len(b)
			n += 1 + l + sovTfhe(uint64(l))
		}
	}
	if len(m.Attesters) > 0 {
		for _, s := range m.Attesters {
			l = len(s)
			n += 1 + l + sovTfhe(uint64(l))
		}
	}
	if m.Status != 0 {
		n += 1 + sovTfhe(uint64(m.Status))
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovTfhe(uint64(m.ExpiresAt))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinAttesters != 0 {
		n += 1 + sovTfhe(uint64(m.MinAttesters))
	}
	if m.DecryptionWindowBlocks != 0 {
		n += 1 + sovTfhe(uint64(m.DecryptionWindowBlocks))
	}
	l = len(m.ServerKey)
	if l > 0 {
		n += 1 + l + sovTfhe(uint64(l))
	}
	return n
}

func sovTfhe(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTfhe(x uint64) (n int) {
	return sovTfhe(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Ciphertext) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTfhe
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ciphertext: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ciphertext: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTfhe(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTfhe
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Attester) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTfhe
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attester: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attester: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = append(m.Pubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.Pubkey == nil {
				m.Pubkey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SharePubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SharePubkey = append(m.SharePubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.SharePubkey == nil {
				m.SharePubkey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTfhe(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTfhe
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DecryptionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTfhe
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DecryptionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DecryptionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CiphertextId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CiphertextId = append(m.CiphertextId[:0], dAtA[iNdEx:postIndex]...)
			if m.CiphertextId == nil {
				m.CiphertextId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partials", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Partials = append(m.Partials, make([]byte, postIndex-iNdEx))
			copy(m.Partials[len(m.Partials)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attesters", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attesters = append(m.Attesters, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTfhe(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTfhe
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTfhe
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAttesters", wireType)
			}
			m.MinAttesters = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinAttesters |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecryptionWindowBlocks", wireType)
			}
			m.DecryptionWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DecryptionWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTfhe
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTfhe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerKey = append(m.ServerKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ServerKey == nil {
				m.ServerKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTfhe(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTfhe
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTfhe(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTfhe
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTfhe
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTfhe
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTfhe
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTfhe
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTfhe        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTfhe          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTfhe = fmt.Errorf("proto: unexpected end of group")
)
